render ( { root: 'root',
           branches: [['root', 'a', 1],
                      ['root', 'b', .5],
                      ['a', 'x', .1],
                      ['a', 'y', .2]],
           rowData: { x: 'AAGGCCAAGGCCAAGGCCAAGGCCAAGGCCAAGGCCAAGGCCAAGGCCAAGGCCAAGGCCAAGGCCAAGGCCAAGGCCAAGGCCAAGGCCAAGGCCAAGGCC',
                      y: 'GAAGTCGAAGTCGAAGTCGAAGTCGAAGTCGAAGTCGAAGTCGAAGTCGAAGTCGAAGTCGAAGTCGAAGTCGAAGTCGAAGTCGAAGTCGAAGTCGAAGTC',
                      b: 'GAGGTTGAGGTTGAGGTTGAGGTTGAGGTTGAGGTTGAGGTTGAGGTTGAGGTTGAGGTTGAGGTTGAGGTTGAGGTTGAGGTTGAGGTTGAGGTTGAGGTT',
                      root: '******************************************************************************************************',
                    },
           rowHeight:24,
//           height:100,
           parent: document.body } )
