/*
const spike_nterm = {
  "name": "Spike glycoprotein N-terminal domain (Pfam PF16451)",
  "root": "node31",
  "branches": [
    ["node25","H9AA65_9BETC/16-292",0.0546674],
    ["node4","SPIKE_CVP67/16-292",0.0069417],
    ["node4","Q2QKN3_9BETC/16-292",0.0154545],
    ["node24","node4",0.0986427],
    ["node23","A0A0K2RVL1_9BETC/16-292",0.181996],
    ["node22","SPIKE_CVHN5/15-288",0.277175],
    ["node21","A0A0A7UZR7_9BETC/17-293",0.321188],
    ["node12","A0A0K1Z074_CVHSA/31-288",0.399544],
    ["node11","SPIKE_CVHSA/82-284",1e-09],
    ["node11","Q1T6X6_CVHSA/82-284",1e-09],
    ["node12","node11",0.581898],
    ["node20","node12",1.14709],
    ["node19","C6GHS2_9BETC/16-290",0.130043],
    ["node18","C0KYS1_9BETC/16-290",0.0647462],
    ["node17","Q9J3E7_9BETC/16-290",0.000524703],
    ["node17","SPIKE_CVMA5/16-290",0.00681283],
    ["node18","node17",0.094657],
    ["node19","node18",0.0735366],
    ["node20","node19",0.279245],
    ["node21","node20",0.0243941],
    ["node22","node21",0.0344464],
    ["node23","node22",0.0561155],
    ["node24","node23",0.0591345],
    ["node25","node24",0.0333859],
    ["node31","node25",0.00565293],
    ["node30","Q4VID5_CVHOC/16-305",0.122166],
    ["node29","B7U2P4_9BETC/16-292",0.0120281],
    ["node29","Q06BD7_9BETC/16-292",0.0172098],
    ["node30","node29",0.0289821],
    ["node31","node30",0.00565293]],
  "rowData": {
    "H9AA65_9BETC/16-292": "IGDLKCT-----TASINDVDTGT-----PPISTATVDVTNGLGTYYVLDRVYLNTTLLLNGYYPISGSTYRNMALKGTLLLSTLWFKPPFLSDFNNGIFAKVKNTKVIKNGVMYSEFPAITIGSTFVNTSYSVVVLPHt----tisd------nkvL----GLLEISVCQYTMCEYP-HTICHPNL-GNKRIELWHFDTDVVSCLYKRNFTYDV---NADFLYFH--FYQEGGTFYAYFTDTGFVTKF------------LFNVYLGTVLSHYYVMPLTCD-------S------TL----SLEYWVTPLTPRQYLLAFNQDGIIFNAADCMSDFMS",
    "SPIKE_CVP67/16-292": "IGDLKCT-----TSLINDVDTGV-----PSISSEVVDVTNGLGTFYVLDRVYLNTTLLLNGYYPISGATFRNMALKGTRLLSTLWFKPPFLSPFNDGIFAKVKNSRFSKDGVIYSEFPAITIGSTFVNTSYSIVVEPHt----slin------gnlQ----GLLQISVCQYTMCEYP-HTICHPNL-GNQRIELWHYDTDVVSCLYRRNFTYDV---NADYLYFH--FYQEGGTFYAYFTDTGFVTKF------------LFKLYLGTVLSHYYVMPLTCN-------S------AL----SLEYWVTPLTTRQFLLAFDQDGVLYHAVDCASDFMS",
    "Q2QKN3_9BETC/16-292": "LGDLKCN-----TSSINDVDTGV-----PSISSEVVDVTNGLGTFYVLDRVYLNTTLLLNGYYPISGATFRNMALKGTRLLSTLWFKPPFLSPFNDGIFAKVKNSRFFKDGVIYSEFPAITIGSTFVNTSYSIVVEPHt----llin------gnlQ----GLLQISVCQYTMCEYP-HTICHPNL-GNQRIELWHYDTDVVSCLYRRNFTYDV---NADYLYFH--FYQEGGTFYAYFTDTGFVTKF------------LFKLYLGTVLSHYYVMPLTCD-------S------AL----SLEYWVTPLTTRQFLLAFDQDGVLYHAVDCASDFMS",
    "A0A0K2RVL1_9BETC/16-292": "VGDVKCT-----TIGVNDVNTGA-----PVISTETVDVTNGLGTYYVLDRVYLNTTLLLNGYYPTSGANYRNLALKASALLSTLWYKPPFLSEFNDGVFAKVKNTKVTKNGIVYSEFPTMVIGTTFVNTSYTVVVQPRt----tvvn------sklQ----GLLEITICQYSMCEYP-NTVCNSGI-GSPRKELWHYEKAVASCLYRRNFTYDV---NSDWLYFH--FYQQGGTFYAYYTDSGFITTF------------LFNIYLGTSLSHYYVVPLSCS-------G------KL----DLQYWVTPLTNRQFLLVFNQDGIIYNAVDCASDYMS",
    "SPIKE_CVHN5/15-288": "IGDFNCT-----NSFINDYNKTI-----PRISEDVVDVSLGLGTYYVLNRVYLNTTLLFTGYFPKSGANFRDLALKGSIYLSTLWYKPPFLSDFNNGIFSKVKNTKLYVNNTLYSEFSTIVIGSVFVNTSYTIVVQPHN----------------------GILEITACQYTMCEYP-HTVCKSK--GSIRNESWHIDSSEPLCLFKKNFTYNV---SADWLYFH--FYQERGVFYAYYADVGMPTTF------------LFSLYLGTILSHYYVMPLTCN-------AISsnTDNE----TLEYWVTPLSRRQYLLNFDEHGVITNAVDCSSSFLS",
    "A0A0A7UZR7_9BETC/17-293": "IGDFKCT-----QSWINSAASPQ-----PPISTEVVDVSNGVGTYYVLNRVYLNTSLLLTGYYPVSGSIYRNLLLKGTQWLSTNWFLPPFLSEFNSGIFVKARNSKPVLNGITHSEFGTIVFGTSFVNTTYTIVIEPStqivn--------------gklIGTLSASVCQYTMCEYP-NTACNPVL-GNGRPSLWHASIGIVPCLYQRNFTYNV---AADNIYFH--FYQDGGTFYAYVGDKSPITTL------------LFQVYLGTVVTHYYVLPLVCN-------A------RQ----TYEYWVTPLIKREYLLVFDGNGVITNAVDCASDHMS",
    "A0A0K1Z074_CVHSA/31-288": "----------------------------sqvs------ssrrgvyynddifrsdvlhltqdyflpfhsnltqyfslsiqsdkivYFDNPIL-KFGDGIYFAATEKSNVIRGWVF--------GSTFDNTTQSAIIVNNS----------------------THIIIRVCYFNLCKDPMYTVS--AG-TQISSWVYQNAFNCTYdrvEKSFQLDTAPKsgnFIAlreFVFKNRDGFFTVYQDYTpvnllrglpaglSVLKPILKLPFGINITSFrVVMAMFSKTT-SNYV------pE----SAAYYVGNLKQSTFMLSFNQNGTITDAVDCSQnpla",
    "SPIKE_CVHSA/82-284": "----------------------------p----------------------------------------------------------------fkdgiyfaateksnvvrGWVF--------GSTMNNKSQSVIIINNS----------------------TNVVIRACNFELCDNPFFAVSKPMG-TQTHTMIFDNaFNCTFEYISDAFSLDVSEKSgnfkhLrEFVFKNKDGFLYVYkgYQpidvvrDlpSGFNTlKPIFKLPLGINITNFRAILTAFSPAQ-diWG------TS----AAAYFVGYLKPTTFMLKYDENGTITDAVDCSQnpla",
    "Q1T6X6_CVHSA/82-284": "----------------------------p----------------------------------------------------------------fkdgiyfaateksnvvrGWVF--------GSTMNNKSQSVIIINNS----------------------TNVVIRACNFELCDNPFFAVSKPMG-TQTHTMIFDNaFNCTFEYISDAFSLDVSEKSgnfkhLrEFVFKNKDGFLYVYkgYQpidvvrDlpSGFNTlKPIFKLPLGINITNFRAILTAFSPAQ-diWG------TS----AAAYFVGYLKPTTFMLKYDENGTITDAVDCSQnpla",
    "C6GHS2_9BETC/16-290": "IGDFRC---------INrVNTSISNARAPSVSTEVVDVSKGLGTYYVLDRVYLNATLLLTGYYPVHGSMYRNMALMGTNTLSLNWFEPPFLSEFNDGIYAKVKNLKASLPIGSASYFPTIIIGSNFVNTSYTVVLEPYN----------------------GIIMASICQYTICQLP-HTYCKPNTgGNTLIGFWHTDLRSPVCILTRNFTFNV---NAEWLYFH--FYQQGGTFYAYYADVSSATTF------------LFSSYIGAVLTQYFVLPYMCNPTTSGVFS------PQ-------YWVTPLVKRQYLFNFNQKGIITSAVDCASSYTS",
    "C0KYS1_9BETC/16-290": "IGDFRC---------IQtVNYNGNNASAPSISTEAVDVSKGLGTYYVLDRVYLNATLLLTGYYPVDGSNYRNLALTGTNTLSLTWFKPPFLSEFNDGIFAKVQNLKTNTPTGATSYFPTIVIGSLFGNTSYTVVLEPYN----------------------NIIMASVCTYTICQLP-YTPCKPNTnGNRVIGFWHTDVKPPICLLKRNFTFNV---NAPWLYFH--FYQQGGTFYAYYADKPSATTF------------LFSVYIGDILTQYFVLPFICTPTAGSTLA------PL-------YWVTPLLKRQYLFNFNEKGVITSAVDCASSYIS",
    "Q9J3E7_9BETC/16-290": "IGDFRC---------IQlVNSNGANVSAPSISTETVEVSQGLGTYYVLDRVYLNATLLLTGYYPVDGSKFRNLALTGTNSVSLSWFQPPYLSQFNDGIFAKVQNLKTSTPSGATAYFPTIVIGSLFGYTSYTVVIEPYN----------------------GVIMASVCQYTICQLP-YTDCKPNTnGNKLIGFWHTDVKPPICVLKRNFTLNV---NADAFYFH--FYQHGGTFYAYYADKPSATTF------------LFSVYIGDILTQYYVLPFICNPTAGSTFA------PR-------YWVTPLVKRQYLFNFNQKGVITSAVDCASSYTS",
    "SPIKE_CVMA5/16-290": "IGDFRC---------IQlVNSNGANVSAPSISTETVEVSQGLGTYYVLDRVYLNATLLLTGYYPVDGSKFRNLALRGTNSVSLSWFQPPYLNQFNDGIFAKVQNLKTSTPSGATAYFPTIVIGSLFGYTSYTVVIEPYN----------------------GVIMASVCQYTICQLP-YTDCKPNTnGNKLIGFWHTDVKPPICVLKRNFTLNV---NADAFYFH--FYQHGGTFYAYYADKPSATTF------------LFSVYIGDILTQYYVLPFICNPTAGSTFA------PR-------YWVTPLVKRQYLFNFNQKGVITSAVDCASSYTS",
    "Q4VID5_CVHOC/16-305": "IGDLNCpldtrLKGSFNNRDTGP-----PSISTDTVDVTNGLGTYYVLDRVYLNTTLFLNGYYPTSGSTYRNMALKGTDKLSTLWFKPPFLSDFINGIFAKVKNTKVFKDGVMYSEFPAITIGSTFVNTSYSVVVQPRt------instqdgvnklQ----GLLEVSVCQYNMCEYP-HTICHPKL-GNHFKELWHLDTGVVSCLYKRNFTYDV---NATYLYFH--FYQEGGTFYAYFTDTGFVTKF------------LFNVYLGMALSHYYVMPLTCI-------S------RLDIGFTLEYWVTPLTSRQYLLAFNQDGIIFNAVDCMSDFMS",
    "B7U2P4_9BETC/16-292": "IGDLKCT-----TVSINDVDTGV-----PSISTDTVDVTNGLGTYYVLDRVYLNTTLLLNGYYPTSGSTYRNMALKGTLLLSTLWFKPPFLSDFTNGIFAKVKNTKVVKDGVMYSEFPAITIGSTFVNTSYSVVVQPHt----tnfd------sklQ----GLLEISVCQYTMCEYP-NTICNPNL-GNQRVELWHWDTGVVSCLYKRNFTYDV---NADYLYFH--FYQEGGTFYAYFTDTGVVTKF------------LFNVYLGTVLSHYYVMPLTCN-------S------AL----TLEYWVTPLTSKQYLLAFNQDGVIFNAVDCKSDFMS",
    "Q06BD7_9BETC/16-292": "IGDLKCT-----TVSINDVDTGV-----PSISTDTVDVTNGLGTYYVLDRVYLNTTLLLNGYYPTSGSTYRNMALKGTLLLSTLWFKPPFLSDFTNGIFAKVKNTKVIKDGVMYSEFPAITIGSTFVNTSYSVVVQPHt----tilg------nklQ----GFLEISVCQYTMCEYP-NTICNSNL-GNRRVELWHWDTGVVSCLYKRNFTYDV---NADYLYFH--FYQEGGTFYAYFTDTGVVTKF------------LFNVYLGTVLSHYYVMPLTCN-------S------AL----TLEYWVTPLTSKQYLLAFNQDGVIFNAVDCKSDFMS"
  }
}
*/

/*
const dde = {
  root: 'root',
  branches: [
    [ 'node1', 'Q112T8_TRIEI/59-200', 0.46854 ],
    [ 'node1', 'B7KLQ4_CYAP7/136-277', 0.22403 ],
    [ 'node2', 'B8M612_TALSN/206-353', 1.40693 ],
    [ 'node2', 'Q3J777_NITOC/19-161', 0.62262 ],
    [ 'node3', 'node2', 0.15499 ],
    [ 'node3', 'node1', 0.33627 ],
    [ 'node4', 'C3KMH7_SINFN/48-190', 0.49604 ],
    [ 'node4', 'C1DG58_AZOVD/44-186', 0.25028 ],
    [ 'node5', 'node4', 0.06679 ],
    [ 'node5', 'Q3SVR1_NITWN/44-186', 0.3309 ],
    [ 'node6', 'B8HLS5_CYAP4/14-156', 0.58897 ],
    [ 'node6', 'B1WNX3_CYAA5/19-161', 0.47743 ],
    [ 'node7', 'node6', 0.22328 ],
    [ 'node7', 'Q5P8V6_AROAE/74-216', 0.36091 ],
    [ 'node8', 'node7', 0.14569 ],
    [ 'node8', 'node5', 0.20621 ],
    [ 'node9', 'A5CDW1_ORITB/138-276', 0.50183 ],
    [ 'node9', 'node8', 0.37567 ],
    [ 'node10', 'node9', 0.09939 ],
    [ 'node10', 'node3', 0.13742 ],
    [ 'node11', 'B8LZ95_TALSN/146-306', 1.41538 ],
    [ 'node11', 'B3MG73_DROAN/322-472', 2.10673 ],
    [ 'node12', 'node11', 0.534 ],
    [ 'node12', 'node10', 0.54887 ],
    [ 'node35', 'B8FA67_DESAA/174-314', 0.84978 ],
    [ 'node35', 'B2J3A3_NOSP7/183-342', 1.04359 ],
    [ 'node13', 'node35', 0.31999 ],
    [ 'node13', 'node12', 0.14564 ],
    [ 'node31', 'B0JUR0_MICAN/39-182', 0.63921 ],
    [ 'node31', 'A8ZPF4_ACAM1/39-182', 0.30855 ],
    [ 'node28', 'node31', 0.42441 ],
    [ 'node28', 'Q2SM05_HAHCH/47-193', 0.66539 ],
    [ 'node14', 'node28', 0.79901 ],
    [ 'node14', 'node13', 0.15953 ],
    [ 'node15', 'B8F0C4_THASP/172-315', 0.57733 ],
    [ 'node15', 'A0R819_PELPD/171-314', 0.3654 ],
    [ 'node16', 'node15', 0.16561 ],
    [ 'node16', 'Q12BS7_POLSJ/169-312', 0.66949 ],
    [ 'node17', 'Q5P1T1_AROAE/182-325', 0.94748 ],
    [ 'node17', 'A1TXP2_MARHV/168-311', 0.39982 ],
    [ 'node18', 'node17', 0.16594 ],
    [ 'node18', 'node16', 0.12196 ],
    [ 'node30', 'A6LRL5_CLOB8/180-328', 1.12742 ],
    [ 'node30', 'node18', 0.36768 ],
    [ 'node19', 'Q6LH76_PHOPR/165-309', 0.40918 ],
    [ 'node19', 'D3VKI2_XENNA/117-263', 0.29264 ],
    [ 'node33', 'node19', 0.68671 ],
    [ 'node33', 'Q10V63_TRIEI/166-315', 1.60582 ],
    [ 'node20', 'Q9K9X4_BACHD/19-163', 0.71816 ],
    [ 'node20', 'node33', 0.27629 ],
    [ 'node21', 'A1WPJ8_VEREI/180-332', 0.49403 ],
    [ 'node21', 'A1VRC2_POLNA/30-181', 0.30377 ],
    [ 'node27', 'node21', 0.14517 ],
    [ 'node27', 'Q01P88_SOLUE/181-333', 0.53324 ],
    [ 'node29', 'node27', 0.52033 ],
    [ 'node29', 'Q8ZSE8_NOSS1/20-198', 0.70812 ],
    [ 'node34', 'A7ILC4_XANP2/116-266', 1.22242 ],
    [ 'node34', 'node29', 1.52935 ],
    [ 'node22', 'node34', 0.189 ],
    [ 'node22', 'node20', 0.05367 ],
    [ 'node23', 'Q5V1W0_HALMA/25-182', 0.97502 ],
    [ 'node23', 'D3T269_NATMM/179-319', 0.40294 ],
    [ 'node24', 'node23', 0.71769 ],
    [ 'node24', 'D2QCC4_SPILD/162-305', 0.84247 ],
    [ 'node26', 'node24', 0.39858 ],
    [ 'node26', 'node22', 0.29225 ],
    [ 'root', 'node26', 0.02808 ],
    [ 'root', 'node25', 0 ],
    [ 'node25', 'node30', 0.10532 ],
    [ 'node25', 'node14', 0.17052 ] ],
  rowData: {
    'B7KLQ4_CYAP7/136-277': 'KRVYLDE.AGFDNRD.DYPYGYSPKGER..CYDLKCGKKRE....RVSWIGALKEGK...ILAP.LTFEGCCNRDLFEA.WLSQSLVPQLEP................GDIIILDNAT..FHKGETIREIVEE...............................AGCELWYL.....PAYSPDLNKIENWWSVLKTWMKQ...MLPEFETVR',
    'Q112T8_TRIEI/59-200': 'SIVYVDE.AGIDNRE.DYSYDYGVKGKR..LPGMKLGKRTE....RVSWIAAINQEK...MFAS.LTFIRSCNRDLFEN.WLEHCLLPKLHP................GQVIIVDNAT..FHKSVDIEELVAK...............................VKCEIWYL.....PPYSPDFNKIERWWFVLKNWIRP...RLKEFKNFR',
    'Q3J777_NITOC/19-161': 'RFVYLDE.SGFEPEV.SRRYAYAPKGRR..VYGLISGHRRP....RTSLLAARMDEG...FEAP.FLFEGTCNTAVFNA.WLEKELCPLLNS................NHIVIMDNAP..FHKAVSSREIIKK...............................TGAGILFL.....PPYSPDFNPIEKDFGNIKKIREY..NEHETLENIV',
    'B8M612_TALSN/206-353': 'DLIFLDE.SIFNEKTGWRRHAYAPIGDD..AEIDADINWGK....TWSICAAMTLEG...YLPCTGIKDGYYSTGDFAD.WLETKLIPALSQIH............QFPMVIVLDNVK..IHTREHVSQIIES...............................AGHLIRYL.....PPYSPNYNPIELTFSVLKSWMKR...NWIFLRETC',
    'Q3SVR1_NITWN/44-186': 'RLVFIDE.TWTKTNM.APLRGWAPRGQR..IRAKVPHGRWQ....TMTFMAALRHDR...ITAP.WFIEGPINGEAFLL.YIEKVLVPTLRH................GDIVIMDNLG..SHKASAVRRVIRA...............................AGARLFYL.....PKYSPDLNPIEQFFAKFKHWLRK..AAQRTTEAVY',
    'C1DG58_AZOVD/44-186': 'KLIFVDE.TAASTNL.ARLRGWAPRGER..CRAAIPHGHWK....TTTFTAGLRVDG...LTAP.LVLDGAMNGPVFLA.YVGQVLVPELTP................GDIVVMDNLP..AHKVAGVRQAIEG...............................AGATLRYL.....PPYSPDLNPIEMAFSKLKALLRK..AAARTVPELW',
    'C3KMH7_SINFN/48-190': 'RLVFIDE.TSTNTKL.TKRSGWAPKGQR..YRAHAPFGSWK....TQTFIAGLRSHG...VVAP.FIVNAPMNRRIFET.WIETQLAPTLSP................GDVVILDNVG..FHKSERAEQMVKA...............................KGAWLLFL.....PPYSPDLNPIEMAFSKLKALLRK..RAARSFDAIA',
    'Q5P8V6_AROAE/74-216': 'RLRFIDE.SGVNIAM.TRHYGRALRGER..VPDAVPKNHGR....NVTLLGAVSCRG...IDAV.MTVEGPTDAAVFRA.YVDQVLVPALAP................GDIVVMDNLS..AHKVKGIRETIEG...............................AQADLLYL.....PPYSPDWSPIEPCWSKLKTALRA..AKARTREALD',
    'B1WNX3_CYAA5/19-161': 'NLVFIDE.SGVNLAM.LRLYARSLKGTR..ARGEKPQKRGH....NISIIGALSLEK...ILAF.ANIYGSVNGVTFEA.FIVTELVPKLWT................GACVVMDNAK..IHLGEIVREAIEE...............................AGASLMYL.....PPYSPEFSPIENFWSKVKAILRK..IKARNYKDLI',
    'B8HLS5_CYAP4/14-156': 'NLVFLDE.MGVLQGM.SRPRGRSRKGQR..VYDLKPFYRGR....RVTVVGAISQTS...ILAM.QTLGKSMTGEDFKQ.FVSEHLVPKLWS................GAVVVMDNLK..AHQVEGIEQMIEA...............................VGARVVYL.....SPYSPEFNPIEHLWWQLKALIRR..FVPKSVEAIT',
    'A5CDW1_ORITB/138-276': '.LVFIDE.SGIEDNA.CREYGWSIKGTR..CYVNKAYQHKS....RVSMIAGLCNNQ...IIAP.VIFEGNCNKEIFTT.YVETILIKELRP................GQIVIMDNIN..FHKNNTIKVLIES...............................VGCSILFL.....PTYSPDLNPIEHYWFKIKNEIRKVTAQFKD.....',
    'B3MG73_DROAN/322-472': 'RVVFHDE.RRFNLDG.PDGFSYYFHDLRNYERTLSQRPRGN....SVYIYLMVCVGG........AVHLEVSSAKQRPESCIEAIMRERPNIVGK...........LGSPEFVLQDHNWMSHALPTAQDLLNA...............................EGLKTQKW.....PTIAHDLNIMENVWGWLIREVFDGGRKFSRKDDLI',
    'B8LZ95_TALSN/146-306': 'SMLFSDF.VNFGLGTTRKAKVFNRKDERLCEDCLQSREEIDKALFHCWAMVGYDYKG...PLIFLETEDNDLSAMSQRD.YISQIIQLHVQPIV............TARRMIYLDNASEVYEHATAPQNMVHAY.............................LDSLHLPYIQ...NPPTSPDLNVLKDVLLLLKKRLQK..RSIGDQIQLK',
    'B2J3A3_NOSP7/183-342': 'QVWFWDE.SGFSLRV.IRRKNWGKKGKR..KN.VLLLRRCG....RVNVMGAIRESD...RKRV.CFFVKKGNADIFYE.QLQQLNELIKQEWASIGNLGKDFSKHGPKIILILDNAS..FHKRKDIIAKISEE.............................FPNFVLEFL.....PAYSPDYNIIELVWHSCKEYIAH..RLFKSVDELQ',
    'B8FA67_DESAA/174-314': 'DIWFADE.SGFDGDP.RPRRRWDKKGRK.....TRSTKNGDH..IRMNVIGMVCPRT...GEFF.AIEATNVFTEMFQV.FLDEAKKCIEFER..............ERNILILDNAT..WHKCKTLNWH...................................GFEPLFL.....PPYSPDLNPIERIWLIMKDRWFN.NHISKDRDALI',
    'Q2SM05_HAHCH/47-193': 'DLYYFDE.SGFSQRS.NLPYGWSPVGQS..TR.LKSYSHSK....RLNVLGFMNRRQ...KLIF.HTTEERVDSAQVVA.LFNKLAESKDPLK...............NAVVLLDNAS..VHRSAEFRRHRWDWM...........................D.KSIWPIYF.....PKYSPELNLIEILWRKVKYNWLP.LGSHETFERLK',
    'A8ZPF4_ACAM1/39-182': 'DLRYLDE.SGFCLVP.YVPYAWQEKGET.L...GLPSQRSS....RFNVLGLMNRHN...DLTS.YVFDKSITSAVVVA.CIDDFSRTCDQ.................HTVVVMDQAS..VHKNAEIEEKIEDW............................KAKNVEIFWL.....PTYSPHLNLIEIFWRFMKYEWIE.FAAYKCLGSLS',
    'B0JUR0_MICAN/39-182': 'EIGYLDE.MGGDSKP.CIPEAWQEEKTT.I...KLPPIEGK....RLNILGIMKRDN...QLFY.ETQVGTVTSEIVIN.FLDKYCQNIQK.................KTVIIIDQAS..IHTSEAFMEKLEEW............................EKKNLKIFWL.....PTYSPHLNLIEILWRFLKYEWIE.FSAYKDRKSLL',
    'Q12BS7_POLSJ/169-312': 'QIYWGDE.MGLRSDH.VSGKSYAPAGQT..PL.IRATGQRF....GCNMISAITNKG...ALAF.MVFEGKFRAPLFVE.FLRRLLKQVEG.................KICLIVDGHP..VHKSGVVKRFVQAN.............................AQRLRLILL.....PGYCPELNPDELLNQDVKTNALG.KSRPANKSEMI',
    'A0R819_PELPD/171-314': 'EIYWGDE.TGIQTGA.NVERGYSPKGKT..PV.LRQTGRKH....RINMISAITNQG...KVRF.MFYKETMNSKRLIT.FMKRLVKDAGR.................KVYLILDNLK..VHHSHVVMDWLEKH.............................KDKIEVFYL.....PSYSPELNPDEYLNNSLKGRVHS.GERAQNVKQLE',
    'B8F0C4_THASP/172-315': 'VIYWADE.TAVKEDT.NWIRGFAPAGRT..PV.LEASARWA....KLSMISAITNRG...EIAF.QIVEGTINAERFIE.FLERLIASAAS.................KVFLIVDNLR..VHHAKLVQAWVETR.............................RAQIELFYL.....PPYAPESNPDEYLNHDFKTALRL.EPPSRDDSQLL',
    'A1TXP2_MARHV/168-311': 'TIYFGDE.ASIRSDY.HSGTTWAPKGET..PI.IRNTGSRF....SINLISAISPRG...ELRF.KTIQGTMNTDAFLG.FLKALVQDADK.................PVFLILDNHP..VHHARRVREYVESL.............................DGKLKLFFL.....PPYSPELNPDESVWGYIKYHHVG.KKIINSKEQLR',
    'Q5P1T1_AROAE/182-325': 'EILFWDE.SGFRADA.VQGRTWGAKGRT..PV.VAVPGQRQ....SISAASAVSMKG...GFWF.AIYPGALNGELFVD.LLRKLMHRRRK.................PLHLVLDGLP..AHKKAGVKTYVAST.............................QGKLTLHFL.....PGYAPDLNPDELVWSHAKRTGNA.RRPLQKGETLQ',
    'A6LRL5_CLOB8/180-328': 'VLYSLDE.TGLRTES.DIRRSWSQIGVS..PI.LESNNSHE....GINIIGATEISKNFDTIMDAYPAKHSIKSHEVEV.FLERLLKIHVGK................KVYVLLDNAK..FHTSRIIQDFADAH.............................SEELFLINT.....PRYSPILNPQENIWNKLKNCIFS.TSAFISIDELF',
    'Q10V63_TRIEI/166-315': 'TVFMIDE.CHLLWGD.ILGYAWGKTDERIE...IAIKNEKE....RQTYYGALDYKT...KEFL.VQEYESGNTKNTIE.FIKYLQKQRPGN................KLAIFWDGAT..YHNSQEFREYLMTIN...........................QYLSEEELLINCTRFAPNAPEQNPVEDIWLQTKNFSIT...FYHLCSSFK',
    'D3VKI2_XENNA/117-263': 'PLLFRDA.VPPSPST.KLSAGGMKAGKNQVKV.AETTGSRT....RLNLMGALNLQQ...IEETVIREYPTINAKNVVL.FFGAIRETYPLSQ...............KIHLILDGAG..YHRSEIVKFFAEV...............................LNIELHYL.....PPYSPNLNPIERLWKYANEQIRN.NVYFPDAKTFR',
    'Q6LH76_PHOPR/165-309': 'PLLFMDA.VHPTQAT.KITAGWVKKGVD..KP.IETTGSRT....RLNIVGAIRLGH...LSEAIVDKYKTVNGESIIA.FLNRTRDFYRASG...............TIHLVLDGAG..YHRSFQVVEEAKK...............................LNIELHYL.....PPYSPNLNPIERLWKVMNKHARN.SRYFATAKEFR',
    'Q9K9X4_BACHD/19-163': 'HLLFQDE.SMIRDYQ.ALQYTWFLKGKQ..RI.IPTYGKHQ....GVKLIGTLNYET...GDVL.CVEEERYDAEAFLR.FLQKVLKHYPTG................KIVMVLDNAR..IHHAKLIEPFLRNH.............................QHRLELVFL.....PPYSPELNLIEGLWKWLKSDVIN.NLFYSSVKEIR',
    'Q8ZSE8_NOSS1/20-198': 'RTISIDEMTGIQATERLEKDLPMRPGKV..ERREFEYIRHG....TQSLIASFDVAT...GQIVEPTCSDTRTEIDFAL.HIRRTIETDTQAK...............KWHLIMDCLN..THQSESLVRLVAEKEGLNLDLGIKGESGILKSMKSRTTFLSDPAHRIVFHYT.....PKHSSWLNQIEIWFSILVRKLLR.RASFLSQDDLK',
    'Q01P88_SOLUE/181-333': 'PVVCLDE.KPVTLHADVRPTSPAKPGRE..ARRDNEYERRG....TANVFCAVEPKA...GRHF.TFATPDRSAFEFAH.VVFELAMQYQQAD...............TIHLVLDNLN..IHCLKSLTDAFGMEMG........................CEVWDRFTIHFT.....PKHGSWLNQAEIEIGLFSRQCLG.KRRIPTLISLR',
    'A1VRC2_POLNA/30-181': 'PVVCMDE.TPRQLIRETREPIAAAPGRP..ERHDYEYERCG....VCNVFMASEPLA...GRRL.TKVTERRTKTDWAV.FVQDIAASYPDAE...............RITLVMDNLN..THTPGSLYEAFSPEQA........................KALWDRFEFVYT.....PKHGSWLNMAEIEINVMVDQCLS..RRIDSIETVR',
    'A1WPJ8_VEREI/180-332': 'PVVCFDE.SPTQLIGEVRQPIPAEPGQP..LRYDYEYKRNG....TANLFVFLDAHR...SWRR.VKVTERRMAQDFAQ.CMRDLVDIHYPQA..............ERIRLVLDNLS..THTAAALYQSMPPQEA........................RRILQRIEFHYT.....PKHASWLNMVEIEIGVLRRQCLD..RRIDCRERLI',
    'A7ILC4_XANP2/116-266': 'VLLYGDE.SEALTHP.YLARAWAKSGAD..LR.VPAPGQAK....NVAMLGSLNHAT...RELI.VQTSPTKRSSDFVA.HLQQLDEAYGPKPGR..........AARPVVLVEDNGP..IHTSKLSRAALAAR.............................AHWLTVEWL.....PKYAPELNDIEAVWRDLKAHHLA.HQTFKDSDALD',
    'D2QCC4_SPILD/162-305': 'VILYIDE.SACYLLP.FVAHTWAPCGQT..PV.LMEQAGRT....HLSLIAAIAANG...QIYV.AGQNQAFTSEDIVW.FLKLLCGRYRKR................NLLIIWDGAA..IHRSNVVKELLRER.............................LGRMHLERL.....PAYSPELNPVELLWSQLKRNLKN..KAFTSLDELT',
    'D3T269_NATMM/179-319': 'TVVCIDQ.TKKSVQV.EPRAAWFPRGTR..PS.VELSGQRD....WTCLLGAITENG...DRFF.TRFEEYVTAAHAKH.FILALCQEFED.................NLIVVLDGAP..YFQASAVTDLAAR...............................DDLTFVRL.....PAYSPELNPVEECWRQLQAALSN..RFFDSLPELT',
    'Q5V1W0_HALMA/25-182': 'TVVVVDQ.FTKHVGT.VQRRGFYPIGSN..PT.IEVATSWD....SVTVLGAVTDNG...DSFF.CWTEENLTRNHGIR.LLEALKDRFGE.................ELVVFLDRAG..YFYARDLWEHVSGERETETVG..............DSSVSCVRGDDLEVWYF.....PSKLPELNAVEGCWDQLQEWFKY..RLVPDISSLK'
  },
}
*/

/*
const rve = {
root: "node171",
  branches: [
    ["node3","O86606_STRCO/115-235",0.527667],
    ["node3","Q8FSL3_COREF/34-150",0.20141],
    ["node13","node3",0.290306],
    ["node12","Y4JA_SINFN/125-259",2.24737],
    ["node11","G2PGW7_STRVO/120-238",0.296354],
    ["node10","TRA9_MYCTU/102-222",0.270642],
    ["node9","Q326M8_SHIDS/37-151",0.193219],
    ["node9","Q82T33_NITEU/30-144",0.138382],
    ["node10","node9",0.0342362],
    ["node11","node10",0.0538944],
    ["node12","node11",0.160042],
    ["node13","node12",0.111661],
    ["node133","node13",0.191715],
    ["node18","Y4601_AGRFC/28-148",0.278332],
    ["node17","C5A8D3_BURGB/109-231",0.309151],
    ["node17","Q7APC2_RHIME/106-228",0.338652],
    ["node18","node17",0.0852042],
    ["node124","node18",1.09384],
    ["node23","A0A1B1P491_STAPS/156-285",0.849547],
    ["node22","A6TIM0_KLEP7/185-325",1.04535],
    ["node22","B7JB79_ACIF2/278-419",1.68948],
    ["node23","node22",0.213167],
    ["node123","node23",0.484785],
    ["node38","POL_RSVSA/1336-1447",0.668122],
    ["node29","POL_HTL1C/1223-1331",0.148644],
    ["node28","POL_HTLV2/1218-1332",0.229402],
    ["node28","POL_HTL32/1198-1309",0.103195],
    ["node29","node28",0.0824902],
    ["node37","node29",0.415891],
    ["node36","W5QF10_SHEEP/660-771",0.445615],
    ["node35","F9W6J4_TRYCI/667-777",0.276824],
    ["node34","POK10_HUMAN/642-756",0.150052],
    ["node34","POL_MMTVC/1493-1603",0.294365],
    ["node35","node34",0.20445],
    ["node36","node35",0.0560977],
    ["node37","node36",0.250123],
    ["node38","node37",0.0387439],
    ["node48","node38",0.234102],
    ["node41","P71644_MYCTU/136-254",1.98129],
    ["node41","POL_HV2BE/1225-1332",0.617838],
    ["node47","node41",0.390806],
    ["node46","POL_WDSV/1482-1596",0.633372],
    ["node45","POL_XMRV6/1443-1557",0.235731],
    ["node45","F9W7M6_TRYCI/366-480",0.155396],
    ["node46","node45",0.537166],
    ["node47","node46",0.302877],
    ["node48","node47",0.239218],
    ["node122","node48",0.170421],
    ["node55","Q8PCY9_XANCP/159-274",0.377157],
    ["node54","Q8P9Q4_XANCP/175-289",0.165564],
    ["node53","Q63YU9_BURPS/105-218",0.154137],
    ["node53","Q9RI26_YERPE/42-157",0.261077],
    ["node54","node53",0.0761076],
    ["node55","node54",0.063567],
    ["node59","node55",0.0980996],
    ["node58","Q72EL5_DESVH/106-218",0.59894],
    ["node58","A6X7G7_OCHA4/41-154",0.519218],
    ["node59","node58",0.0457829],
    ["node95","node59",0.537035],
    ["node68","INTG_SPV1R/173-280",1.28129],
    ["node67","Q4JWM1_CORJK/216-324",0.462107],
    ["node66","INSI4_ECOLI/226-337",0.151529],
    ["node65","O53337_MYCTU/180-292",0.773458],
    ["node65","TRA8_CUPMC/175-287",0.0896439],
    ["node66","node65",0.229901],
    ["node67","node66",0.195067],
    ["node68","node67",0.105986],
    ["node94","node68",1.01217],
    ["node93","I6X5T4_MYCTU/115-244",1.37551],
    ["node92","Q3L9G2_RHOE4/119-243",1.42336],
    ["node91","Q5LF59_BACFN/170-296",0.929863],
    ["node80","Y3428_MYCTU/53-175",1.03091],
    ["node79","B4E7R1_BURCJ/140-272",0.13009],
    ["node78","Y4UI_SINFN/137-270",0.165519],
    ["node77","Y4BL_SINFN/140-273",0.528372],
    ["node77","A4VHC8_PSEU5/128-259",0.233773],
    ["node78","node77",0.142846],
    ["node79","node78",0.38173],
    ["node80","node79",0.288697],
    ["node90","node80",0.364096],
    ["node89","O69924_STRCO/154-280",1.12671],
    ["node88","Q9RI04_YERPE/30-157",0.606709],
    ["node87","A0A0A1BBC9_9GAMM/130-256",1.1685],
    ["node86","B7GM82_ANOFW/119-243",0.553963],
    ["node86","Q7ARN5_YERPE/118-242",0.442641],
    ["node87","node86",0.143205],
    ["node88","node87",0.149835],
    ["node89","node88",0.166391],
    ["node90","node89",0.0482136],
    ["node91","node90",0.215258],
    ["node92","node91",0.161519],
    ["node93","node92",0.260378],
    ["node94","node93",0.504712],
    ["node95","node94",0.377227],
    ["node121","node95",0.234241],
    ["node102","YJ41B_YEAST/620-742",1.0084],
    ["node101","E7KRB4_YEASL/2-117",0.943078],
    ["node100","YD11B_YEAST/660-782",0.889915],
    ["node100","K4CL29_SOLLC/120-235",0.734899],
    ["node101","node100",0.0537477],
    ["node102","node101",0.156867],
    ["node116","node102",0.201237],
    ["node109","YAGA_ECOLI/137-258",0.839534],
    ["node108","Q4JUC9_CORJK/130-281",0.200124],
    ["node107","O86758_STRCO/130-269",0.320283],
    ["node107","O86023_CLAMS/137-276",0.638638],
    ["node108","node107",0.199057],
    ["node109","node108",0.536178],
    ["node115","node109",0.229786],
    ["node114","INTG_SPV1C/179-314",1.12698],
    ["node113","A3N0V8_ACTP2/160-284",0.943176],
    ["node113","Q9KTS1_VIBCH/132-242",1.06025],
    ["node114","node113",0.14064],
    ["node115","node114",0.141947],
    ["node116","node115",0.085324],
    ["node120","node116",0.20274],
    ["node119","P71639_MYCTU/157-273",0.8143],
    ["node119","O28959_ARCFU/127-246",0.873384],
    ["node120","node119",0.120084],
    ["node121","node120",0.0826088],
    ["node122","node121",0.0426424],
    ["node123","node122",0.0258679],
    ["node124","node123",0.318347],
    ["node132","node124",0.206167],
    ["node131","I6YC39_MYCTU/135-252",0.850854],
    ["node130","I3U489_ENTFC/38-151",0.726388],
    ["node129","Q3XXA7_ENTFC/55-164",0.259556],
    ["node129","Q5HK26_STAEQ/66-174",0.265163],
    ["node130","node129",1.95357],
    ["node131","node130",0.175519],
    ["node132","node131",0.0866492],
    ["node133","node132",0.0860359],
    ["node171","node133",0.0107476],
    ["node142","Q03B13_LACP3/103-218",0.809067],
    ["node137","F9VEV0_LACGL/68-184",0.170222],
    ["node137","Q8E0T3_STRA5/107-222",0.169839],
    ["node141","node137",0.352719],
    ["node140","P73967_SYNY3/53-168",0.36288],
    ["node140","Q7M7F9_WOLSU/234-344",0.21716],
    ["node141","node140",0.283484],
    ["node142","node141",0.0116237],
    ["node170","node142",0.0796858],
    ["node151","K7XY25_MYCHR/36-152",0.242974],
    ["node150","INSK_ECOLI/117-234",0.227544],
    ["node149","Q8DYF6_STRA5/114-228",0.3846],
    ["node148","Y1721_HAEIN/54-170",0.226699],
    ["node148","Q9CB06_LACLA/105-225",0.660469],
    ["node149","node148",0.0590859],
    ["node150","node149",0.0582325],
    ["node151","node150",0.0670237],
    ["node169","node151",0.399651],
    ["node154","Q03XH7_LEUMM/40-147",0.612794],
    ["node154","Q7DAW1_LACLA/116-233",0.382713],
    ["node168","node154",0.128376],
    ["node157","T904_LACLA/91-207",0.359323],
    ["node157","Q32H63_SHIDS/71-186",0.483931],
    ["node167","node157",0.0921464],
    ["node166","A6X1S5_OCHA4/107-219",0.436029],
    ["node165","Q328A8_SHIDS/106-222",0.485697],
    ["node164","Q6FCT6_ACIAD/110-224",0.342532],
    ["node163","Q7CM18_LEPIN/121-236",0.156369],
    ["node163","Q8CLY2_LEPIN/105-221",0.15601],
    ["node164","node163",0.2445],
    ["node165","node164",0.0480121],
    ["node166","node165",0.0638348],
    ["node167","node166",0.0271649],
    ["node168","node167",0.0379331],
    ["node169","node168",0.0270534],
    ["node170","node169",0.0300796],
    ["node171","node170",0.0107476]],
  rowData: {
    "O86606_STRCO/115-235": "--------A--------A-QM------P-------N-T------KN---V-GD-ITC------L-------------P---VG---N-GQ----F--------------------------------L------Y----LATVLDLCSKRLTGW--SIAD--------H-MPTSL---------VTDVLRA-AA---R----A-R-G---------------------GDG---L----R--G---------A---ISH--SGN-----------G-AQY---V------S--------KE--------F--------------AQVCSELGVTRSRGAVGTSADKAAAESLNTT-MKRGT----",
    "Q8FSL3_COREF/34-150": "--------A--------D-K-------P-------N-Q------LY---V-GD-ITY------L-------------P---IA---D-GS----N--------------------------------M------Y----LATVIDCYSRRLVGF--SIAD--------H-MRTSL---------VQDALLM-AK---G----Q-R-G---------------------N-----L----K--G---------A---IFH--SDH-----------G-SVY---T------S--------NA--------F--------------QDACKDLGIKQSMGSIGTSADNALAESFNAA-LKRE-----",
    "Y4JA_SINFN/125-259": "-------QT--------H-E-------P-------G-R------LG---L-SD-FTD------M-------------G---SL---S-V-----T--------------------------------I------A----GQPLDHLLYHFRLVW--SGFE--------H-AHVILGGESFVA--LAEGLQN-AL---W----S-V-----------------------G-----G----S--P---------L---YHR--SDSLSAAFRNLDADA-KVD---L------T--------NR--------Y--------------EELCAHYRMTPTRNNKGVAHENGSIESSHGH-LKNAV----",
    "G2PGW7_STRVO/120-238": "--------A--------S-R-------P-------D-Q------LW---V-AD-MTY------V-------------R---TW---S-G-----W--------------------------------A------Y----VAFVLDVYSRMIVGW--QVAN--------H-MRTEL---------PLDALEM-AL---W----R-R-----------------------R-----IKKD-S--G---------L---IHH--SDR-----------G-SQY---V------S--------IR--------Y--------------TDRLSDIGASASVGSVADSYDNAMAEALNGT-FKAEL----",
    "TRA9_MYCTU/102-222": "--------P--------P-A-------P-------N-R------LW---V-AD-LTY------V-------------S---TW---A-G-----F--------------------------------A------Y----VAFVTDAYARRILGW--RVAS--------T-MATSM---------VLDAIEQ-AI---W----T-R-----------------------Q-----Q----E--GVLDLKD---V---IHH--TDR-----------G-SQY---T------S--------IR--------F--------------SERLAEAGIQPSVGAVGSSYDNALAETINGL-YKTE-----",
    "Q326M8_SHIDS/37-151": "--------A--------E-R-------P-------D-Q------LW---V-AD-FTY------V-------------S---TW---Q-G-----F--------------------------------V------Y----VAFIIDVFAGYIVGW--RVSS--------S-METTF---------VLDALEQ-AL---W----A-R-----------------------R-----P----S--G---------T---VHH--SDK-----------G-SQY---V------S--------LA--------Y--------------TQRLKEAGLLASTGSTGDSYDNAMAESINGL-YKAE-----",
    "Q82T33_NITEU/30-144": "-----------------N-R-------P-------N-Q------LW---V-SD-FTY------V-------------S---TW---Q-G-----W--------------------------------L------Y----VAFVIDVFARRIVGW--RVSS--------T-MSTDF---------VLDALEQ-AL---Y----D-R-----------------------R-----P----A--D---------TL--IHH--SDR-----------G-SQY---V------S--------IR--------Y--------------TERLAQAGIEPSVGSRGDSYDNALAETINGL-YKAE-----",
    "Y4601_AGRFC/28-148": "-------------------R-------S-------N-L------RW---C-SDGLEF------A-------------C---WN---G-E-----V--------------------------------I------R----LAFIIDAFDREIIAWT-AVANAGISGS--D-VRDMM---------LE-AVEK-RF---H----A-T-----------------------R-----A----P--H---------A---I-EHLSDN-----------G-SAY---T------A--------RD--------T--------------RLFAQALNLTPCFTPVASPQSNGMSEAFVKT-LKRD-----",
    "C5A8D3_BURGB/109-231": "--------V--------E-R-------S-------N-Q------RW---C-SDGFEF------R-------------C---DN---G-E-----P--------------------------------L------R----VTFALDCCDREAMSW--AATTAGHSGD--I-VRDVM---------LA-AVES-RFG--D----V-L-----------------------H-----T----E--S---------E---I-EWLSDN-----------G-SGY---T------A--------EE--------T--------------RQFAALLGLKPLTTPVCSPQSNGMAESFVKT-MKRD-----",
    "Q7APC2_RHIME/106-228": "--------V--------E-R-------S-------N-I------RW---C-SDGFEI------G-------------C---DN---K-E-----K--------------------------------V------R----VAFALDCCDREAIAH--VATTEGIKSQ--D-VQDLV---------IT-AVEN-RFG--R----I-N-----------------------M-----L----S--E---------P---I-EWLTDN-----------G-SCF---I------A--------KD--------T--------------ASLLRDIGMEPCTTPVRSPQSNGMAEAFVKT-FKRD-----",
    "A0A1B1P491_STAPS/156-285": "------S-S----------R-------P-------N-E------IW---Q-AD-HTL------L----DIFILDQ--K---GN---I-N-----R--------------------------------P------W----LTIIMDDYSRAIAGY--FLSF--------D-APNAQ---------NT-ALTL-HQ---A----I-W--NKN--------DT---NWPVCG-----I----P--E---------K---F-Y--TDH-----------G-SDF---T------S--------HH--------M--------------EQVAIDLKINLMFSKVGVPRGRGKIERFFQT-V-NQT----",
    "A6TIM0_KLEP7/185-325": "------V-T----------A-------P-------L-E------QV---Q-ID-HTV------I----DLIVVDDRDR---QP---I-G-----R--------------------------------P------Y----LTLAIDVFTRCVLGM--VVTL--------E-APSAV---------SV-GLCL-VH---V----A-C--DKRPWLEGLNVEM---DWQMSG-----K----P--L---------L---L-Y--LDN-----------A-AEF---K------S--------EA--------L--------------RRGCEQHGIRLDYRPLGQPHYGGIVERIIGTAM-QMI----",
    "B7JB79_ACIF2/278-419": "------V-G------------------P-------A-S------RY---Q-ID-ATI------A----DVYLVSRYDR---TK---IVG-----R--------------------------------P------V----LYIVIDVFSRMITGV--YVGF--------E-GPSWV---------GA-MMAL-SN---T----A-T--EKVEYCRQFGVEIGAADWPCQA-----L----P--D---------A---L-L--GDR-----------G--EI---A------G--------SA--------I--------------ETLINNFQVRVENAAPYRADWKGIVEQRFRL-I-PAR----",
    "POL_RSVSA/1336-1447": "-------------------G-------P-------L-Q------IW---Q-TD-FTL------E-------------P---RM---A-P-----R--------------------------------S------W----LAVTVDTASSAIVVT--QHGR--------V-TSVAA---------QH-HWAT-AI---A----V-L-----------------------G-----R----P--K---------A---I-K--TDN-----------G-SCF---T------S--------KS--------T--------------REWLARWGIAHTTGIPGNSQGQAMVERANRL-LKDKI----",
    "POL_HTL1C/1223-1331": "---------------------------P-------N-H------IW---Q-GD-ITH------F-------------K---YK---N-T-----L--------------------------------Y------R----LHVWVDTFSGAISAT--QKRK--------E-TSSEA---------IS-SLLQ-AI---A----Y-L-----------------------G-----K----P--S---------Y---I-N--TDN-----------G-PAY---I------S--------QD--------F--------------LNMCTSLAIRHTTHVPYNPTSSGLVERSNGI-LKT------",
    "POL_HTLV2/1218-1332": "-------------------R-GLL---P-------N-H------IW---Q-GD-VTH------Y-------------K---YK---K-Y-----K--------------------------------Y------C----LHVWVDTFSGAVSVS--CKKK--------E-TSCET---------IS-AVLQ-AI---S----L-L-----------------------G-----K----P--L---------H---I-N--TDN-----------G-PAF---L------S--------QE--------F--------------QEFCTSYRIKHSTHIPYNPTSSGLVERTNGV-IKN--LL--",
    "POL_HTL32/1198-1309": "---------------------GHA---P-------N-D------IW---Q-GD-VTH------L-------------Q---YK---R-Y-----K--------------------------------Y------C----LLVWVDTYSGAVSVS--CRRK--------E-TGSDC---------VA-SLLV-AI---S----I-L-----------------------G-----K----P--Q---------N---I-N--TDN-----------G-AAY---L------S--------QE--------F--------------QQFCNSLAIKHSTHIPYNPTSSGLVERTNGI-LKT------",
    "W5QF10_SHEEP/660-771": "------------------LR-------P-------N-H------LW---Q-TD-VTH------I-------------P---QF---G-R-----L--------------------------------K------Y----VHVSIDTFSNFLMAS--LHTG--------E-STRHC---------IQ-HLLF-CF---S----T-S-----------------------G-----I----P--Q---------T---L-K--TDN-----------G-PGY---T------S--------RS--------F--------------QRFCLSFQIHHKTGIPYNPQGQGIVKRAHQR-LKHQ-----",
    "F9W6J4_TRYCI/667-777": "-------------------R-------P-------L-Q------VW---Q-MD-VTH------V-------------S---SF---G-K-----L--------------------------------Q------Y----LHVSIDTCSGIMFAS--PLTG--------E-KASHV---------IQ-HCLE-AW---S----A-W-----------------------G-----K----P--R---------L---L-K--TDN-----------G-PAY---T------S--------QK--------F--------------QQFCRQMDVTHLTGLPYNPQGQGIVERAHRT-LKAY-----",
    "POK10_HUMAN/642-756": "-------------------R----GLCP-------N-A------LW---Q-MD-VTH------V-------------P---SF---G-R-----L--------------------------------S------Y----VHVTVDTYSHFIWAT--CQTG--------E-STSHV---------KK-HLLS-CF---A----V-M-----------------------G-----V----P--E---------K---I-K--TDN-----------G-PGY---C------S--------KA--------F--------------QKFLSQWKISHTTGIPYNSQGQAIVERTNRT-LKTQ---L-",
    "POL_MMTVC/1493-1603": "-------------------K-------P-------R-V------LW---Q-MD-VTH------V-------------S---EF---G-K-----L--------------------------------K------Y----VHVTVDTYSHFTFAT--ARTG--------E-ATKDV---------LQ-HLAQ-SF---A----Y-M-----------------------G-----F----P--Q---------K---I-K--TDN-----------A-PAY---V------S--------RS--------I--------------QEFLARWKISHVTGIPYNPQGQAIVERTHQN-IKAQ-----",
    "P71644_MYCTU/136-254": "------E-A--------P-K-------V-------P-G------VI---E-AD-TVA------HCGP----------S---LI---G-E-----F--------------------------------A------R----TLTMTDLVTGWTENA--SIRN--------N-AAKWI---------LE-GIKE-CQ---Q----R-F-----------------------P-----F----P--M-----------TVF-D--SDC-----------G-GEF---I------N--------HD--------V--------------AGWLQARDIAQTRSRPYQKNDQAHVESKNNH-VVRKH----",
    "POL_HV2BE/1225-1332": "------N-A--------E-----------------I-G------VW---Q-MD-YTH------LEGK-------------------------------------------------------------------I----IIVAVHVASGFIEAE--VIPQ--------E-SGRQT---------AL-FLLK-LA---S----R-W-----------------------P-----I----T--H-------------L-H--TDN-----------G-PNF---T------S--------QE--------V--------------KMVAWWVGIEQSFGVPYNPQSQGVVEAMNHH-LKNQI----",
    "POL_WDSV/1482-1596": "------L-P--------S-R-------P-------F-A------HL---Q-ID-FVQ------MCVK----------K---PM---------------------------------------------------Y----ALVIIDVFSKWPEII--PCNK--------E-DAKTV---------CD-ILMKDII---P----R-W-----------------------G-----L----P--D---------Q---I-D--SDQ-----------G-THF---T------A--------KI--------S--------------QELTHSIGVAWKLHCPGHPRSSGIVERTNRT-LKSKI----",
    "POL_XMRV6/1443-1557": "--------G--------H-R-------P-------G-T------HW---E-VD-FTE------V--K----------P---GL---Y-G-----Y--------------------------------K------Y----LLVFVDTFSGWVEAF--PTKR--------E-TAKVV---------SK-KLLEDIF---P----R-F-----------------------G-----M----P--Q---------V---L-G--SDN-----------G-PAF---A------S--------QV--------S--------------QSVADLLGIDWKLHCAYRPQSSGQVERMNRT-IK-ET----",
    "F9W7M6_TRYCI/366-480": "--------G--------D-H-------P-------G-V------YW---E-VD-FTE------V--K----------P---GM---Y-G-----N--------------------------------K------Y----LLVFVDTFSGWVEAF--PTKT--------E-TAQIV---------AK-KILEEIL---P----R-F-----------------------G-----I----P--K---------V---I-G--SDN-----------G-PAF---V------A--------QV--------S--------------QGLATQLGINWKLHCAYRPQSSGQVERMNRT-LK-ET----",
    "Q8PCY9_XANCP/159-274": "--PS--Q-A--------------------------N-Q------VW---S-MD-FVF-----DR-------------T---AE---G-R-----V--------------------------------I------K----CLVIVDDATHEAVAI--EVER--------A-ISGHG---------VT-RVLD-RL---A----H-SR----------------------G-----L----P--K---------V---I-R--TDN-----------G-KEF---C------G--------KA--------M--------------VAWAHARNVQLRLIQPGKPNQNAYVESFNGR-LRDEC----",
    "Q8P9Q4_XANCP/175-289": "---S--M-P--------------------------N-D------TW---S-MD-FVF-----DA-------------L---AN---A-R-----R--------------------------------I------K----CLTVVDDFTRESVDI--AVDH--------G-ISGAY---------VV-RLLD-QA---A----C-FR----------------------G-----Y----P--R---------A---V-R--TDN-----------G-PEF---T------S--------RA--------F--------------IAWTQQHGIEHILIEPGAPTQNAYIESFNGK-FRDEC----",
    "Q63YU9_BURPS/105-218": "------A-P--------------------------N-E------VW---S-ID-FVM-----DA-------------L---SN---G-R-----R--------------------------------V------K----CLTVVDDFTKEAVDI--VVDH--------G-ISGLY---------VA-RALD-RA---A----R-FR----------------------G-----Y----P--K---------A---V-R--TDQ-----------G-PEF---T------S--------RA--------L--------------DQWAYANGVTLKLIQAGKPTQNAYIESFNGK-FRDEC----",
    "Q9RI26_YERPE/42-157": "--PA--A-P--------------------------N-L------TW---S-MD-FVM-----DA-------------L---AT---G-R-----R--------------------------------I------K----CLTCVDDYTKECLTV--TVAF--------G-ISGVQ---------VT-RILD-SI---A----L-FR----------------------G-----Y----P--A---------T---I-R--TDQ-----------G-PEF---T------C--------RA--------L--------------DQWAFEHGVELRLIQPGKPTQNGFIESFNGR-FRDEC----",
    "Q72EL5_DESVH/106-218": "------C-A--------------------------N-V------CW---S-ID-FMH-----DA-------------L---AS---G-Q-----R--------------------------------F------R----TFNVLDDFSRECLAI--EVDT--------N-LPAAR---------VL-RVLD-RI---V----A-WR----------------------G-----L----P--A---------K---L-R--MDN-----------G-PEL---I------S--------VL--------L--------------ADWAEKNGVALEFIQPGKPTQNSYIERFNKT-YREE-----",
    "A6X7G7_OCHA4/41-154": "------R-A--------------------------N-A------RW---S-LD-FVH-----DQ-------------F---AC---G-R-----R--------------------------------F------R----VLNIVDDVTRECLAA--IPDT--------S-ISGRR---------VA-RELT-DL---I----S-RR----------------------G-----K----P--G---------M---I-V--SDH-----------G-TEF---T------S--------NA--------I--------------LAWSKDHRVEWHYIAPGKPMQNGYVESFNGR-MRDEL----",
    "INTG_SPV1R/173-280": "-------------------------------------G------WL---E-MD-T--------V-------------V---GK---D-H-----K--------------------------------S------A----ILVLVEQLSKKYFAI--KLEN--------H-TAREV---------EK-KFKD-II-IKN----N-LI----------------------G-----K----I--K---------G---I-I--TDR-----------R-KEF---S------K--------W------------------------REMEIFAETQVYFCDAGSPQQKPLIEYMNSE-LRHWF----",
    "Q4JWM1_CORJK/216-324": "-----------------------------------P-G------HW---E-GD-L--------V-------------I---GK---G-G-----K--------------------------------S------A----LITLVERTSRYTLLG--HLPD------E-H-SSHTV---------VA-TLQD-MV---K----D-LN----------------------T--E--Q----L--K---------T---I-T--WDQ-----------G-AEM---A------V--------T------------------------AQVQIKDGCQVFFCEPHSPWQRPTNENTNGE-IRRRF----",
    "INSI4_ECOLI/226-337": "----------------------------DNRRS--L-G------HW---E-GD-L--------V-------------S---GT---K-N--------------------------------------S------H----IATLVDRKSRYTIIL--RLRG--------K-DSVSV---------NQ-ALTD-KF---L----S-LP----------------------S--E--L----R--K---------S---L-T--WDR-----------G-MEL---A------R--------H------------------------LEFTVSTGVKVYFCDPQSPWQRGTNENTNGL-IRQYF----",
    "O53337_MYCTU/180-292": "----------------------------ADRSE--P-G------HW---E-GD-L--------I-------------V---GK---N-Q-----G--------------------------------S------A----IGTLVERQTRLIRLL--HLPT--------H-DAYCL---------RI-AITE-TM---S----D-LP----------------------V--T--L----V--R---------S---I-T--WDQ-----------G-IEM---A------R--------H------------------------IDITADLGAPVYFCDSRSPWQRASNENSNGL-LRQYF----",
    "TRA8_CUPMC/175-287": "----------------------------NDRLM--P-G------HW---E-GD-L--------I-------------K---GA---G-N-----Q--------------------------------S------A----VGVLVERMSRAVLLV--KMPD--------A-TAASA---------LA-GFTG-KL---Q----S-LV----------------------A--P--L----R--Q---------T---L-T--YDQ-----------G-REM---A------R--------H------------------------AELSAATGVRVYFCDPHSPWQRGTCENTNGL-LRQYL----",
    "I6X5T4_MYCTU/115-244": "------A------------------------------GEIAQCDFWFP-P-IE-L-------PV-------------G---FG---Q-T-----R--------------------------------T------AKQLPVLTMVCAYSRWLLAM--LLPS--------R-CAEDL---------FA-GWWR-LI---E----A-LG----------------------A-----V----P--R---------V---L-V--WDG-----------E-GAI---G------R--------W-----------RGG-RSE-LTTECQAFRGTLAAKVLICRPADPEAKGLIERAHDY-L-ERS----",
    "Q3L9G2_RHOE4/119-243": "----V-T-E--------------------------P-GLWLQYDFG---D-G----------PT-------------I---SG---R-------K--------------------------------T------T----LFCAWLAWSRFRVVI--PIWD--------K-TLPTV---------AA-CLDA-TF---R----R-LG----------------------G-----V----P--V---------Y---V-L--TDN-----------EKTAT---I------D--------H-----------VAG-IAV-RNPEIVEVARHYGTTLRTCLPADPESKGGSEATVRI-AKAD-----",
    "Q5LF59_BACFN/170-296": "-------------------------------------GEYAQADFG---E-KW-I-------PV---K---------N---GG---S-T-----K--------------------------------V------Y----FFAIVLTRSRYKFIH--FSRR--------PFDTELA---------IY-AHEL-AF---Q----Y-FG----------------------G-----R----P--E---------K---I-I--YDQ-----------DRVLI---A------R--------E-----------NLG-DLI-LTGKFQSFIKEQHFQPVFCRRSDPESKGKVENVVKY-VKENF----",
    "Y3428_MYCTU/53-175": "------------------------------------------IDYG---R-LG-M--WFD--PA-------------T---AR---R-V-----A--------------------------------V------W----AFVMVLAFSRHLFVR--PVIR--------M-DQTAW---------CA-CHVA-AF---E----F-FD----------------------G-----V----P--A---------R---L-V--CDN-----------LRTGV---D------K--------P-----------DLY-DPQ-INRSYAELASHYATLVDPARARKPKDKPRVERPMTY-VRDSF----",
    "B4E7R1_BURCJ/140-272": "------Q-Q------------------------HRA-GEKLFADFA---G-PT-V-------PV-------------L---AS---D-G-----G--------------------------------VEFEA--H----VFVAVLGASNNTFAC--ATRT--------E-TMADW---------IG-SLCD-AL---E----F-IG----------------------G-----V----P--E---------L---L-V--PDN-----------PKALI---A------R--------P-----------DRY-EPG-LGTTTQDFVNHYGTAMLPARPRKPQDKAKVEVGVQI-VERW-----",
    "Y4UI_SINFN/137-270": "------Q-S------------------------HAG-GEKLFVDYA---G-DK-V-------AV-------------V---DR---K-T-----G--------------------------------VVRDA--H----IFVAVMGASSLSFAL--ATWS--------E-QLPDW---------IE-AHNA-AY---R----F-FG----------------------G-----V----T--Q---------L---L-V--SDN-----------TKCAV---I------K--------A-----------CHF-DPM-VNRSYTDMARHYSTAVFPARPRKPRDKAKVENCVGI-VERWL----",
    "Y4BL_SINFN/140-273": "------N-R------------------------HAA-GAVMQTDYA---G-PT-V-------PV-------------I---DP---A-T-----G--------------------------------VIHPA--Q----IFVAVLGASNLTFAH--ASFS--------Q-QLPDW---------ID-GQVR-AL---T----F-YG----------------------G-----V----T--K---------A---I-V--CDN-----------LKSGV---A------K--------A-----------LWF-EPT-LTATFAAMAEHYDTTILPTRSRKPRDKGRVEGAVLI-VERWI----",
    "A4VHC8_PSEU5/128-259": "------E--------------------------HRV-GEKLFVDYA---G-QT-V-------PV-------------I---DR---H-S-----G--------------------------------EIRRA--Q----VFVAVLGASSYTFAE--ATWS--------Q-QLPDW---------LG-SHTR-CF---A----F-LG----------------------G-----V----P--E---------I---V-V--PDN-----------LRSAV---S------K--------A-----------HRY-EPD-INPSYRDLAEHYGVAVVPARARKPRDKAKAEVGVQV-VERW-----",
    "O69924_STRCO/154-280": "------A-Q--------------------------A-----QVDWG--DE-GK-I-------LA-------------H---VG---I-P-----K--------------------------------V------Y----SFHMTLSYSRDPFCC--FTTS--------Q-DLATF---------FD-CHRK-AF---A----H-FG----------------------G-----V----P--M---------S---V-V--YDR-----------TKTVV---R------R--------H----------VAPG-EAVPLHPEAVAFAGHYDFDIDVLAAYRPQGKGRVERQVGI-VRDHV----",
    "Q9RI04_YERPE/30-157": "-----ET-Q--------------------------P-GYQLQHDWG---E-VE-L-------EV-------------A---GQ---R-C-----K--------------------------------V------N----FAVNTLGFSRRFHVF--AAPK--------Q-DAEHT---------YE-SLVR-AF---R----Y-FG----------------------G-----S----V--K---------T---V-L--VDN-----------QKAAV---L------K--------N-----------NNG-KVV-FNSGFLLLAEHYDFLPRACRPRRARTKGKVERMVKY-LKDN-----",
    "A0A0A1BBC9_9GAMM/130-256": "------A-C----------------------------GEAFQFDWS---E-DF-A-------RI-------------A---GK---Q-V-----K--------------------------------L------Q----IAQFKLAHSRAFVLR--AYYQ--------Q-KHEML---------FD-AHWH-AF---Q----I-FG----------------------G-----I----P--K---------R---G-I--YDN-----------MKTAV---D------S--------V-----------GRGKERR-VNQRFTAMVSHYLFDAQFCNPASGWEKGQIEKNVQD-SRQR-----",
    "B7GM82_ANOFW/119-243": "--------------------------------------EQMQVDWK---EVGE-V-------VI-------------E---GK---K-V-----K--------------------------------L------S----LFVAVLGYSRMKYAV--FTTS--------Q-DQEHL---------ME-CLIQ-SF---K----Y-FG----------------------G-----V----P--K---------K---V-L--FDN-----------MKTVT---D------G--------R-----------EQG-VVK-WNQRFSEFASYYGFIPKVCRPYRAQTKGKVERAIQY-IMDHF----",
    "Q7ARN5_YERPE/118-242": "------T-E--------------------------P-GRQMQVDWG----------------TM-------------R---NG---R-S-----P--------------------------------L------H----VFVAVLGYSRMLYIE--FTDN--------M-RYDTL---------ET-CHRN-AF---R----F-FG----------------------G-----V----P--R---------E---V-L--YDN-----------MKTVVLQRD------A--------Y-----------QTG-QHR-FHPSLWQFGKEMGFSPRLCRPFRAQTKGKVERMVQY-TRN------",
    "YJ41B_YEAST/620-742": "------T-D--------H-E-------P-------G-S------SW---C-MD-I-----FGPV-------------S---SSNA-D-T-----K--------------------------------R------Y----MLIMVDNNTRYCMTS--THFN--------K-NAETI---------LA-QVRK-NI---Q-YVETQF-----------------------D-----R----K-VR---------E---I-N--SDR-----------G-TEF---T------N--------DQ--------I--------------EEYFISKGIHHILTSTQDHAANGRAERYIRT-IITDA----",
    "E7KRB4_YEASL/2-117": "---------------------------------------------V---Q-AD-L-----CGGF-------------R---YQEF-Q-S-----N--------------------------------K------Y----FLTIRDAYSRYYSVI--HLKS--------K-ADASI-------KFME-WINE-TE---Q-YFSSRG-----------------------G-----F----K-VG---------F---V-R--TDN-----------G-TEF---V------N--------KN--------L--------------HAFFESKGIEHQLTIPYHSYQNGAVERAHRT--IEER----",
    "YD11B_YEAST/660-782": "------N-S----YEPFQ--------------------------YL---H-TD-I-----FGPV-------------H---NLPN-S-A-----P--------------------------------S------Y----FISFTDETTKFRWVY--PLHD--------R-REDSI---------LD-VFTT-IL---A-FIKNQF-----------------------Q-----A----S-VL---------V---I-Q--MDR-----------G-SEY---T------N--------RT--------L--------------HKFLEKNGITPCYTTTADSRAHGVAERLNRT-LLDDC----",
    "K4CL29_SOLLC/120-235": "------I-L--------D--------------------------LV---Y-SD-V-----CGPM-------------E---IESI-G-G-----N--------------------------------K------Y----FVTFIDDASRKKWVY--IL----------R-TKDQV---------FQ-VFQK-FH---A-LIERET-----------------------G-----R----K-LK---------R---L-R--TDN-----------G-GEY---T------S--------RE--------F--------------EEYCSNHGIRHEKTVPGTPQHNGVAERMNRT-IVEK-----",
    "YAGA_ECOLI/137-258": "------E-H--------D-A-------P-------N-R------LW---Q-MD-FK-----GHF-------------P---FG---G-G-----R--------------------------------C------H----PLTLLDDHSRFSLCL--AHCT--------D-ERRET---------VQ---QQ-LV---S-VFER-Y-----------------------G-----L----P--D---------R---M-T--MDN-----------G-SPW---GDTTGT-W--------TA--------L--------------ELWLMRLGIRVGHSRPYHPQTQGKLERFHRS-LKAEV----",
    "Q4JUC9_CORJK/130-281": "------E-H--------P-H-------P-------G-S------LI---H-VD-VTK---FGNI-------------P---DG---G-G-----HRYVGRQQGARNKLATPGLPRGKDHKP--RTGTA------F----VHTVIDDHSRVAYAE--IWSD--------E-QASTA---------VG-VLER-AV---A-WFAE-R-----------------------G-----V----T-VE---------R---V-L--SDN-----------G-SAY--------R-S--------HA--------W--------------RDFCARLGIRHKRTRPYRPQTNGKIERFHRT-LGDGW----",
    "O86758_STRCO/130-269": "------E-R--------A-R-------P-------G-E------LV---H-ID-VKK---LGRI-------------P---DG---G-G-----HKTLGRAEGHRSR--------------TNGAGWA------Y----LHTALDDHSRIAYTE--DLPD--------E-TAPTC---------AA-FLVR-AT---A-YFAS-L-----------------------G-----I----R-IE---------R---V-L--TDN-----------A-WAY--------S-K--------NT--------W--------------RNTCRDLDISPRWTRPWRPQTNGKVERFHRT-LLDEW----",
    "O86023_CLAMS/137-276": "------E-H--------E-H-------P-------G-D------LI---H-VD-VKK---LGRI-------------P---DG---G-G-----WRVHGRSEQVRGR----------------GIGFD------Y----VHAAVDDHTRLAYAE--IHPD--------E-KGATA---------AG-FLTR-AA---A-YFAG-H-----------------------G-----I---TR-IE---------R---V-I--TDN-----------A-FAY--------RHS--------TA--------F--------------KNAVQDLGARQKFIRPHCPWQNGKVERFNRT-LATEW----",
    "INTG_SPV1C/179-314": "--------Y--------E-V-------K-------EIG------LL---Q-MD-AKY---FVPS-------------K-FSVD-----K-----K--------------------------------Y------Y----VYDFIDEKTRLALGY--VYDK--------L-STDNA---------ID-AVKK-AI---SDFKNI-F-----------------------G-----I----I-IT---------R---I-R--TDN-----------G-SEF---INNY-R-N--------NQKISVKKTNF--------------TQFLTDKNILHQTTPVRSPQSNGKIERFHQN-YTKLF----",
    "A3N0V8_ACTP2/160-284": "--------T--------A-H-------P-------G-Y------LG---S-QD-TFY---VGNL-------------K---GV-----G-----R--------------------------------I------Y----QQTFVDTYSKVAFAK--LYTM--------K-TAIAA---------AD-MLND-KV---LPFFEA-Q-----------------------G-----L----P-ML---------R---I-L--TDR-----------G-SEY---CGKV-E-N--------HD--------Y--------------ELYLAINDIEHTKTKVKHPQTNGICERFHKT-ILQEF----",
    "Q9KTS1_VIBCH/132-242": "--------R--------P-I-------P-------G-D------RV---Q-MD-TCK---IAP-------------------------------G--------------------------------I------Y----QYTAIDDCSRYRVLR--CYSR--------R-TAANT---------VD-FIDC-VV-------EE-M-----------------------P-----F----P-IQ---------R---I-Q--TDR-----------G-REF---FAE--------------K--------V--------------QKQLMIYGIKFRPNKPGSPHLNGKVERSQKT-DKSE-----",
    "P71639_MYCTU/157-273": "------E-A--------E-H-------P-------N-A------LW---T-GD-VLH-----GI-------------R---ID---L-R-----K--------------------------------T------Y----LFAFLDDHSRLVPGY--RWGH-------AE-DTVRL---------AA-ALRP-AL---A----S-R-----------------------G-----V----P--N---------A---V-Y--VDN-----------G-SPY---V------D--------AW--------L--------------LRACAKLGVRLVHSTPGRPQGRGKIERFFRT-VREQF----",
    "O28959_ARCFU/127-246": "------E-R--------T-H-------S-------M-S------LW---Q-GD-WKR-----------------------------L-G-----E--------------------------------K------W----IIAFMDDASRFITCY-GVFDS--------A-TTENT---------IR-VLKV-GF---R----E-Y-----------------------G-----I----P--D---------E---I-L--TDH-----------G-TQF---V------AAKSREKAKHR--------F--------------REFLAENGVRHVLARINHPQTNGKIERFFGL-MEQKI----",
    "I6YC39_MYCTU/135-252": "--------A--------H-Q-------P-------N-S------VW---S-WD-ITK------L-------------R---GP---A-K-----W--------------------------------S----YYY----LYVILDIFSRYVVGW--MVAS--------R-ESKVL---------AERLIAQ-TL---A----A-Q-----------------------H-----I----S--A------DQLT---L-H--ADR-----------G-SSM---S------S--------KP--------V--------------ALLLADLGVTKSHSRPHTSNDNPLSEAQFKT-LK--Y----",
    "I3U489_ENTFC/38-151": "-----------------D-N-------P-------L-E------AI---V-TD-LTY------V-------------R---VG---K-K-----W--------------------------------N------Y----VCFILDLFNREILGY--SCGE--------H-KDAVL---------VKKAFSR-IK---Q----P-L-----------------------T-----E----V--E---------I---F-H--TDR-----------G-KEF---D------N--------QA--------I--------------DELLTTFDINRSLSHKGCPFDNAVAESTYKS-LKVEF----",
    "Q3XXA7_ENTFC/55-164": "-----------------K-K-------S-------F-Y------SW---K-MD-ETY------I-------------K---IK---G-K-----W--------------------------------H------Y----LYRAIDADGLTLDIW---LRK--------K-RDTQA---------AYAFLKR-LV---K----Q-F-----------------------D-----E----P--K---------V---V-V--TDK-----------A-PSI---T------S---------A--------F--------------KK-LKEYGFYQGTEHRTIKYLNNLIEQDHRP-VKRR-----",
    "Q5HK26_STAEQ/66-174": "---------H-------K-K-------A-------Y-Y------KW---R-ID-ETY------I-------------K---IK---G-K-----W--------------------------------S------Y----LYRAIDAEGHTLDIW---LRK--------Q-RDNHS---------AYAFIKR-LI---K----Q-F-----------------------G-----K----P--Q---------K---V-I--TDQ-----------A-PST---K------V---------A--------M--------------AKVIKAFKLKPDC-HCTSKYLNNLIEQDHRH-IK-------",
    "Q03B13_LACP3/103-218": "-----------------F-K-------P-------F-E------AL---S-SD-ITQ------T-------------T---TS---E-G-----K--------------------------------A------Y----ICQIRDLNSNLVLAH--QISN--------H-MDTDL---------VLATLKQ-AH---Q----R-W-----------------------A-----L----PE-T---------C---IFH--SDR-----------G-SQY---T------A--------KA--------V--------------TKLVNQYHWQRSFSALGKPGDNAWSESFFAI-MKKEL----",
    "F9VEV0_LACGL/68-184": "----------P------N-S-------P-------N-Q------VW---T-TD-FTY------I-------------S---IG--PK-R-----H--------------------------------V------Y----LCAILDLYSRKCIAW--KVSD--------R-IDAKL---------ACDTLEI-AI---N----K-R-----------------------K-----P----KE-P---------I---IFH--SDQ-----------G-SQF---K------S--------AS--------F--------------RKLLDEHQLLASYSKPGYPYDNAVTEVFFKY-LKQR-----",
    "Q8E0T3_STRA5/107-222": "-----------------D-K-------P-------N-Q------VW---S-TD-FTY------I-------------S---IG--YK-K-----Y--------------------------------V------Y----LCAILDLYSRKCIAW--KLSH--------R-MDAKL---------ACNTLEL-AL---N----K-R-----------------------K-----I----EG-T---------L---LFH--SDQ-----------G-SQF---K------A--------RE--------F--------------RKIIDDNNIMHSFSKPGYPYDNAVTEAFFKY-LKHR-----",
    "P73967_SYNY3/53-168": "-----------EI----N-R-------A-------N-Q------VW---C-TD-ITY------L-------------P---IG---K-G-----Y--------------------------------Y------Y----LVVIMDWYSRRVLSW--RISN--------T-MDVKF---------CCNALEE-AL---E----K-Y-----------------------G-----K----P------------E---IFN--SDQ-----------G-SQF---T------S--------KE--------F--------------TQILLQAEVKISMDGRGRCFDNIFIERLWRS-LKYEL----",
    "Q7M7F9_WOLSU/234-344": "-----------------N-R-------A-------N-Q------VW---S-GD-ITY------I-------------P---IK---G-G-----F--------------------------------V------Y----LCAIIDWHSKTILSW--KIST--------T-MDTSL---------VTDVLKE-AI---E----K-Y-----------------------D-----I----P------------V---IFN--SDQ-----------G-SQY---T------S--------HE--------H--------------TELLKKHNIQISMNGKGRSIDNIAIERFFRT-LK-------",
    "K7XY25_MYCHR/36-152": "--------A--------T-Q-------P-------N-Q------KW---T-TD-VTE------F-------------S---GP---F-G-----K--------------------------------A------Y----LSPILDMFNGEVIAW--DLST--------S-ANNQQ---------IRKMLQR-AF---S----K-H-----------------------K-----N----LE-G---------L---IFH--SDQ-----------G-WQY---Q------H--------KQ--------F--------------SEKLKQKGITQSMSRKGNCLDNSVIESFFGT-LKREC----",
    "INSK_ECOLI/117-234": "-K------A--------T-R-------P-------N-E------KW---V-TD-VTE------F-------------A---VN---G-R-----K--------------------------------L------Y----LSPVIDLFNNEVISY--SLSE--------R-PVMNM---------VENMLDQ-AF---K----K-L-----------------------N-----P----HE-H---------P---VLH--SDQ-----------G-WQY---R------M--------RR--------Y--------------QNILKEHGIKQSMSRKGNCLDNAVVECFFGT-LKSEC----",
    "Q8DYF6_STRA5/114-228": "--------G--------S-K-------P-------Y-E------KC---Y-TD-VTE------F-------------A---LP---E-G-----K--------------------------------L------Y----LSPVLDGYNSEIIDF--TLSR--------S-PDLKQ---------VQTMLER-AF---P----A-A-----------------------S-----Y----SE-----------T---ILH--SDQ-----------G-WQY---Q------H--------KS--------Y--------------HQFLEDKGIRPSMSRKGNSPDNGMMESFFGI-LKSE-----",
    "Y1721_HAEIN/54-170": "-T------A--------T-Q-------P-------N-E------KW---T-TD-ITE------F-------------K---CA---E-G-----K--------------------------------L------Y----LSPIKDLFNNEIIAY--DLAR--------S-PNFEQ---------ITRMMKQ-AV---A----R-L-----------------------E-----G----AK-----------P---ILH--SDQ-----------G-WQY---Q------M--------IG--------Y--------------QNILRENGIQQSMSRKGNCLYNSAMESFFGR-LKTEC----",
    "Q9CB06_LACLA/105-225": "-S------I------------------P-------H-Q------KI---T-TD-TTE------F-------------K---YY---E-D-GIQKK--------------------------------C------Y----LNPYIDLFNSEVISY--HISK--------Q-PSYQS---------IDIALNQ-AL---A----V-T-----------------------S---DCP----YR-----------R---TFH--SDQ-----------G-WGY---Q------M--------RD--------Y--------------VSKLKSHRIFQSMSRKGNCHDNSVMENFFGL-LKQEI----",
    "Q03XH7_LEUMM/40-147": "--------------------------------------------VL---T-TD-ITY------I-------------QL--MN---R-N-----W--------------------------------V------Y----LATVYDPEKRRVVSY--GLSS--------E-MTKEF---------ATSVVVK-AL---R----A-N-----------------------G-----K----PK---------------MIH--SDM-----------G-SQY---T------S--------SL--------F--------------EGTLQNAGIDQS--RKGHPYDNARIESFHSL-IKREL----",
    "Q7DAW1_LACLA/116-233": "E-------P--------T-K-------K-------N-K------VW---S-TD-ITY------I-------------P---TQ---Q-G-----W--------------------------------A------Y----LSTIMDRYTKKVIAW--DLGK--------R-MTVEL---------VQRTLNK-AI---K----S-Q-----------------------D-----Y----PE-A---------V---ILH--SDQ-----------G-SQY---T------S--------LE--------Y--------------EELLKYYGMTHSFSRRGYPYHNASLESWHGH-LKREW----",
    "T904_LACLA/91-207": "--------A--------T-A-------P-------N-K------VW---L-GD-MTY------I-------------P---TK---E-G-----T--------------------------------L------Y----LAVNIDVFSRKIVGW--SMSS--------R-MQDKL---------VRDCFLQ-AC---G----K-E-----------------------H-----P----QP-G---------L---IVH--TDQ-----------G-SQY---T------S--------SR--------Y--------------QSTLRQVGAQSSMSRKGNPYDNAMMESFYKT-LKREL----",
    "Q32H63_SHIDS/71-186": "--------P--------T-A-------P-------N-Q------VW---V-AD-LTY------V-------------A---TQ---E-G-----W--------------------------------L------Y----LAGIKDVYTCEIVGY--AMGE--------R-MTKEL---------TGKALFM-AL---R----S-Q-----------------------R-----P----PA-G---------L---IHH--SDR-----------G-SQY---C------A--------YD--------Y--------------RVIQEQSGLKTSMSRKGNCYDNAPMESFWGT-LKNE-----",
    "A6X1S5_OCHA4/107-219": "-----------------E-A-------P-------D-T------AW---V-TD-ITY------I-------------R---TC---E-G-----F--------------------------------A------Y----LAVVIDLYSRRVIGW--AMQS--------R-QTTDV---------VLQALLM-AV---W----R-R-----------------------K-----P----KD-K---------V---LIH--SDQ-----------G-SQF---T------S--------MD--------W--------------ALFLRHHNLVHSMSRRGNCHDNAVAESFFNL-LK-------",
    "Q328A8_SHIDS/106-222": "--------V--------T-E-------P-------N-Q------VW---C-GD-VTY------I-------------W---TG---K-R-----W--------------------------------A------Y----LAVVLDLFARKPVGW--AMSF--------S-PDSRL---------TIKALKM-AW---E----I-R-----------------------S-----K----PA-G---------V---MFH--SDQ-----------G-SHY---T------S--------RQ--------F--------------RQLLWRYQIKQSLSRRGNCWDNSPMERFFRS-LKNEW----",
    "Q6FCT6_ACIAD/110-224": "-----------------N-E-------P-------N-K------IW---T-TD-ITY------I-------------R---TK---Q-G-----W--------------------------------L------Y----LCVMLDLFSRRIVGW--QTSH--------R-IDRQL---------VCDAFHY-AM---A----R-Q-----------------------G-----Y----PM-G---------V---MVH--SDQ-----------G-SQY---C------S--------RD--------F--------------RALLLTNNCVQSMSRRGNCWDNAVTESFFHT-LKGH-----",
    "Q7CM18_LEPIN/121-236": "--------P--------N-Q-------K-------N-R------IW---V-SD-ITF------L-------------R---SS---F-G-----W--------------------------------I------Y----LCVILDLYSRKVVGW--SISN--------S-NDSKL---------VCTALSK-AI---E----C-R-----------------------N-----P----PK-G---------L---VFH--SDR-----------G-SNY---C------S--------YE--------T--------------RRYLLNNKLRRSNSRKGNCWDNAVAESFFGS-LKRE-----",
    "Q8CLY2_LEPIN/105-221": "--------P--------N-E-------Q-------N-R------IW---V-SD-VTF------I-------------R---TS---F-G-----W--------------------------------S------Y----LCVILDLYSRKTVGW--SLSD--------R-NDSQL---------VCDTVLK-AV---L----S-R-----------------------N-----P----RK-G---------L---IFH--SDR-----------G-SNF---C------S--------KE--------T--------------RRLLITNGIRRSNSRKGNCWDNAVAESFFSY-LKRE----I"
  }
}
